import type { DialogueLine, DialogueChoice, QuestDef, QuestReward } from './types';

const dialogues: Record<string, DialogueLine> = {
  eileen_first_meet: {
    id: 'eileen_first_meet',
    speaker: '艾琳',
    text: '你终于醒了！我在废墟旁发现了昏迷的你。这片森林最近变得很危险...',
    next: 'eileen_first_meet_2',
    portrait: 'eileen',
  },
  eileen_first_meet_2: {
    id: 'eileen_first_meet_2',
    speaker: '艾琳',
    text: '我是艾琳，这片翠影森林的守林人。你看起来不像本地人，是从外面来的吗？',
    next: 'eileen_first_meet_3',
    portrait: 'eileen',
  },
  eileen_first_meet_3: {
    id: 'eileen_first_meet_3',
    speaker: '艾琳',
    text: '不管你从哪来，你现在需要武器和装备。我这里有些基础物资可以给你。',
    next: 'eileen_first_meet_4',
    action: 'give_items:iron_sword,health_potion*3',
    portrait: 'eileen',
  },
  eileen_first_meet_4: {
    id: 'eileen_first_meet_4',
    speaker: '艾琳',
    text: '森林深处有一棵古老的树灵，它最近变得狂暴不安。如果你能平息它，也许能找到你失去的记忆线索。',
    next: 'eileen_first_meet_5',
    portrait: 'eileen',
  },
  eileen_first_meet_5: {
    id: 'eileen_first_meet_5',
    speaker: '艾琳',
    text: '往北走就能找到它。小心点，流浪者。',
    action: 'set_flag:forest_quest_start,add_quest:forest_boss',
    portrait: 'eileen',
  },

  eileen_after_boss: {
    id: 'eileen_after_boss',
    speaker: '艾琳',
    text: '你做到了！古树灵终于安息了...它体内竟然藏着这样的碎片！',
    next: 'eileen_after_boss_2',
    portrait: 'eileen',
  },
  eileen_after_boss_2: {
    id: 'eileen_after_boss_2',
    speaker: '艾琳',
    text: '这是...星核碎片！传说中陨星的核心散落在了世界各地。',
    next: 'eileen_after_boss_3',
    portrait: 'eileen',
  },
  eileen_after_boss_3: {
    id: 'eileen_after_boss_3',
    speaker: '艾琳',
    text: '我能感受到碎片中蕴含的力量。也许收集所有碎片，就能揭开陨星灾变的真相。',
    next: 'eileen_after_boss_4',
    portrait: 'eileen',
  },
  eileen_after_boss_4: {
    id: 'eileen_after_boss_4',
    speaker: '艾琳',
    text: '东边的灼沙荒漠中，我感应到了另一块碎片的气息。如果你要前往那里，请多加小心。',
    action: 'set_flag:forest_boss_defeated,unlock_region:desert',
    portrait: 'eileen',
  },

  eileen_generic: {
    id: 'eileen_generic',
    speaker: '艾琳',
    text: '需要什么帮助吗？我可以为你补充一些物资。',
    choices: [
      { text: '告诉我关于这片森林的事', next: 'eileen_forest_info' },
      { text: '我要购买物资', next: 'eileen_shop' },
      { text: '没什么，再见', next: '' },
    ],
    portrait: 'eileen',
  },

  eileen_forest_info: {
    id: 'eileen_forest_info',
    speaker: '艾琳',
    text: '翠影森林曾经是这片大陆上最安宁的地方。自从陨星降临后，森林中的生物都变得暴躁了。',
    next: 'eileen_forest_info_2',
    portrait: 'eileen',
  },
  eileen_forest_info_2: {
    id: 'eileen_forest_info_2',
    speaker: '艾琳',
    text: '古树灵是森林的守护者，但星核碎片的力量扭曲了它的意志。现在它已经安息，森林应该会慢慢恢复。',
    portrait: 'eileen',
  },

  eileen_shop: {
    id: 'eileen_shop',
    speaker: '艾琳',
    text: '这是我目前能提供的物资。',
    action: 'open_shop',
    portrait: 'eileen',
  },

  gregor_first_meet: {
    id: 'gregor_first_meet',
    speaker: '格雷',
    text: '嘿！你是新来的冒险者？我是格雷，这片林子里唯一的铁匠。',
    next: 'gregor_first_meet_2',
    portrait: 'gregor',
  },
  gregor_first_meet_2: {
    id: 'gregor_first_meet_2',
    speaker: '格雷',
    text: '看你那把武器...还能用，但需要好好打磨。我可以帮你强化装备，只要你带来材料。',
    next: 'gregor_first_meet_3',
    portrait: 'gregor',
  },
  gregor_first_meet_3: {
    id: 'gregor_first_meet_3',
    speaker: '格雷',
    text: '森林里的那些怪物身上有时候会掉落铁矿石，收集来给我，我就能帮你升级武器。',
    action: 'add_quest:collect_iron',
    portrait: 'gregor',
  },

  gregor_generic: {
    id: 'gregor_generic',
    speaker: '格雷',
    text: '需要强化装备吗？把材料交给我吧。',
    choices: [
      { text: '强化武器(需要3个铁矿石)', next: 'gregor_upgrade_weapon_yes', condition: 'has_items:iron_ore*3' },
      { text: '强化武器(需要3个铁矿石)', next: 'gregor_upgrade_weapon_no', condition: '!has_items:iron_ore*3' },
      { text: '告诉我关于锻造的事', next: 'gregor_forging_info' },
      { text: '以后再说', next: '' },
    ],
    portrait: 'gregor',
  },

  gregor_upgrade_weapon_yes: {
    id: 'gregor_upgrade_weapon_yes',
    speaker: '格雷',
    text: '好材料！让我来...',
    action: 'remove_items:iron_ore*3,upgrade_weapon',
    portrait: 'gregor',
  },
  gregor_upgrade_weapon_no: {
    id: 'gregor_upgrade_weapon_no',
    speaker: '格雷',
    text: '材料不够啊，再去收集些铁矿石吧。',
    portrait: 'gregor',
  },

  gregor_forging_info: {
    id: 'gregor_forging_info',
    speaker: '格雷',
    text: '锻造是一门古老的手艺。好的材料加上精湛的技术，就能打造出无坚不摧的武器。',
    portrait: 'gregor',
  },

  kashim_first_meet: {
    id: 'kashim_first_meet',
    speaker: '卡西姆',
    text: '又一个闯入灼沙的旅人...我是卡西姆，沙漠中的行商。',
    next: 'kashim_first_meet_2',
    portrait: 'kashim',
  },
  kashim_first_meet_2: {
    id: 'kashim_first_meet_2',
    speaker: '卡西姆',
    text: '这片沙漠下面埋藏着古代文明的遗迹。最近遗迹中传来了奇怪的震动...',
    next: 'kashim_first_meet_3',
    portrait: 'kashim',
  },
  kashim_first_meet_3: {
    id: 'kashim_first_meet_3',
    speaker: '卡西姆',
    text: '如果你要深入遗迹，小心蝎皇——它是沙漠的霸主，守护着遗迹深处的秘密。',
    next: 'kashim_first_meet_4',
    portrait: 'kashim',
  },
  kashim_first_meet_4: {
    id: 'kashim_first_meet_4',
    speaker: '卡西姆',
    text: '我在这片绿洲有些补给品，你需要的话可以看看。',
    action: 'add_quest:desert_boss',
    portrait: 'kashim',
  },

  kashim_after_boss: {
    id: 'kashim_after_boss',
    speaker: '卡西姆',
    text: '蝎皇被击败了？不可思议...你比我见过的任何冒险者都要强。',
    next: 'kashim_after_boss_2',
    portrait: 'kashim',
  },
  kashim_after_boss_2: {
    id: 'kashim_after_boss_2',
    speaker: '卡西姆',
    text: '你在遗迹深处发现的那些符文...它们讲述了一个关于\'虚空之门\'的故事。',
    next: 'kashim_after_boss_3',
    portrait: 'kashim',
  },
  kashim_after_boss_3: {
    id: 'kashim_after_boss_3',
    speaker: '卡西姆',
    text: '北方的霜寂雪原中，隐居着一位贤者。她或许能解读这些符文的含义。',
    action: 'set_flag:desert_boss_defeated,unlock_region:snow',
    portrait: 'kashim',
  },

  vera_first_meet: {
    id: 'vera_first_meet',
    speaker: '薇拉',
    text: '我等你很久了，流浪者。星核碎片的指引不会出错。',
    next: 'vera_first_meet_2',
    portrait: 'vera',
  },
  vera_first_meet_2: {
    id: 'vera_first_meet_2',
    speaker: '薇拉',
    text: '我是薇拉，最后的星术师。我一直在等待被星核选中的人。',
    next: 'vera_first_meet_3',
    portrait: 'vera',
  },
  vera_first_meet_3: {
    id: 'vera_first_meet_3',
    speaker: '薇拉',
    text: '你手中的星核碎片，是封印虚空之门的钥匙。千年前，先民们用五块碎片封印了连接虚空的裂隙。',
    next: 'vera_first_meet_4',
    portrait: 'vera',
  },
  vera_first_meet_4: {
    id: 'vera_first_meet_4',
    speaker: '薇拉',
    text: '但陨星再次降临，碎片散落，封印正在瓦解。虚空生物已经开始渗透到我们的世界。',
    next: 'vera_first_meet_5',
    portrait: 'vera',
  },
  vera_first_meet_5: {
    id: 'vera_first_meet_5',
    speaker: '薇拉',
    text: '你必须收集所有碎片，重新封印虚空之门。否则，这个世界将被虚空吞噬。',
    next: 'vera_first_meet_6',
    portrait: 'vera',
  },
  vera_first_meet_6: {
    id: 'vera_first_meet_6',
    speaker: '薇拉',
    text: '冰龙守护着第三块碎片。它曾经是这片雪原的守护神，但虚空的力量也侵蚀了它。',
    action: 'set_flag:learned_truth,add_quest:snow_boss',
    portrait: 'vera',
  },

  vera_after_boss: {
    id: 'vera_after_boss',
    speaker: '薇拉',
    text: '冰龙终于解脱了...第三块碎片已经归位。',
    next: 'vera_after_boss_2',
    portrait: 'vera',
  },
  vera_after_boss_2: {
    id: 'vera_after_boss_2',
    speaker: '薇拉',
    text: '我感应到废墟中的第四块碎片正在被虚空力量侵蚀。你必须尽快前往那里。',
    next: 'vera_after_boss_3',
    portrait: 'vera',
  },
  vera_after_boss_3: {
    id: 'vera_after_boss_3',
    speaker: '薇拉',
    text: '但我要告诉你一件事...星核碎片与你的联系并非偶然。你本身，就是陨星的一部分。',
    action: 'set_flag:ruins_boss_defeated,unlock_region:ruins,set_flag:player_truth_revealed',
    portrait: 'vera',
  },

  noah_first_meet: {
    id: 'noah_first_meet',
    speaker: '诺亚',
    text: '哦！一个活人！我是诺亚，古代机械的研究者。',
    next: 'noah_first_meet_2',
    portrait: 'noah',
  },
  noah_first_meet_2: {
    id: 'noah_first_meet_2',
    speaker: '诺亚',
    text: '这些废墟是千年前\'星落文明\'的遗迹。他们建造了封印虚空之门的装置。',
    next: 'noah_first_meet_3',
    portrait: 'noah',
  },
  noah_first_meet_3: {
    id: 'noah_first_meet_3',
    speaker: '诺亚',
    text: '核心控制室在废墟最深处，但那里现在被虚空吞噬者占据了。',
    next: 'noah_first_meet_4',
    portrait: 'noah',
  },
  noah_first_meet_4: {
    id: 'noah_first_meet_4',
    speaker: '诺亚',
    text: '我可以教你一些高级战斗技巧，帮助你应对更强的敌人。',
    action: 'teach_skill:thunder,add_quest:ruins_boss',
    portrait: 'noah',
  },

  noah_after_boss: {
    id: 'noah_after_boss',
    speaker: '诺亚',
    text: '虚空吞噬者被击退了！但封印装置...已经严重损坏。',
    next: 'noah_after_boss_2',
    portrait: 'noah',
  },
  noah_after_boss_2: {
    id: 'noah_after_boss_2',
    speaker: '诺亚',
    text: '第四块碎片虽然回收了，但封印已经无法简单修复。你需要前往暮光圣城。',
    next: 'noah_after_boss_3',
    portrait: 'noah',
  },
  noah_after_boss_3: {
    id: 'noah_after_boss_3',
    speaker: '诺亚',
    text: '那里有最后的封印节点。但圣城...已经不再神圣了。虚空的力量正在腐蚀那里的一切。',
    action: 'set_flag:ruins_boss_defeated,unlock_region:holy_city',
    portrait: 'noah',
  },

  guard_captain_first_meet: {
    id: 'guard_captain_first_meet',
    speaker: '守卫长',
    text: '站住！你是谁？圣城不欢迎外来者。',
    next: 'guard_captain_first_meet_2',
    portrait: 'guard_captain',
  },
  guard_captain_first_meet_2: {
    id: 'guard_captain_first_meet_2',
    speaker: '守卫长',
    text: '...等等，你身上有星核碎片的气息。你就是预言中的流浪者？',
    next: 'guard_captain_first_meet_3',
    portrait: 'guard_captain',
  },
  guard_captain_first_meet_3: {
    id: 'guard_captain_first_meet_3',
    speaker: '守卫长',
    text: '圣城正在堕落。堕落圣者——曾经的圣城之主——被虚空力量侵蚀，已经疯了。',
    next: 'guard_captain_first_meet_4',
    portrait: 'guard_captain',
  },
  guard_captain_first_meet_4: {
    id: 'guard_captain_first_meet_4',
    speaker: '守卫长',
    text: '他在大教堂中制造虚空裂缝，试图彻底打开虚空之门。你必须阻止他！',
    next: 'guard_captain_first_meet_5',
    portrait: 'guard_captain',
  },
  guard_captain_first_meet_5: {
    id: 'guard_captain_first_meet_5',
    speaker: '守卫长',
    text: '但你要知道...如果封印虚空之门，你作为陨星的一部分，可能也会随之消散。',
    action: 'add_quest:final_boss',
    portrait: 'guard_captain',
  },

  guard_captain_after_boss_good: {
    id: 'guard_captain_after_boss_good',
    speaker: '守卫长',
    text: '虚空之门被封印了...但流浪者，你...',
    next: 'guard_captain_after_boss_good_2',
    portrait: 'guard_captain',
  },
  guard_captain_after_boss_good_2: {
    id: 'guard_captain_after_boss_good_2',
    speaker: '守卫长',
    text: '你还在！也许...也许你与这个世界的联系，比与虚空的联系更加深厚。',
    next: 'guard_captain_after_boss_good_3',
    portrait: 'guard_captain',
  },
  guard_captain_after_boss_good_3: {
    id: 'guard_captain_after_boss_good_3',
    speaker: '守卫长',
    text: '感谢你，流浪者。世界因你而得救。',
    action: 'set_flag:ending_good',
    portrait: 'guard_captain',
  },

  guard_captain_after_boss_bad: {
    id: 'guard_captain_after_boss_bad',
    speaker: '守卫长',
    text: '你...你释放了虚空之力！这个世界...',
    next: 'guard_captain_after_boss_bad_2',
    portrait: 'guard_captain',
  },
  guard_captain_after_boss_bad_2: {
    id: 'guard_captain_after_boss_bad_2',
    speaker: '守卫长',
    text: '不...也许这就是命运。虚空与这个世界，本就是一体。',
    next: 'guard_captain_after_boss_bad_3',
    portrait: 'guard_captain',
  },
  guard_captain_after_boss_bad_3: {
    id: 'guard_captain_after_boss_bad_3',
    speaker: '守卫长',
    text: '新的时代开始了...但这是好是坏，只有时间能告诉我们。',
    action: 'set_flag:ending_bad',
    portrait: 'guard_captain',
  },

  boss_tree_spirit_pre: {
    id: 'boss_tree_spirit_pre',
    speaker: '古树灵',
    text: '谁...敢...踏入...我的...领地...',
    next: 'boss_tree_spirit_pre_2',
    portrait: 'tree_spirit',
  },
  boss_tree_spirit_pre_2: {
    id: 'boss_tree_spirit_pre_2',
    speaker: '古树灵',
    text: '痛苦...无尽的痛苦...碎片...在灼烧...',
    action: 'start_boss:ancient_tree_spirit',
    portrait: 'tree_spirit',
  },
  boss_tree_spirit_post: {
    id: 'boss_tree_spirit_post',
    speaker: '古树灵',
    text: '谢谢你...流浪者...我终于...可以安息了...带上...这块碎片...',
    action: 'give_items:star_fragment',
    portrait: 'tree_spirit',
  },

  boss_scorpion_king_pre: {
    id: 'boss_scorpion_king_pre',
    speaker: '蝎皇',
    text: '嘶嘶...又有猎物送上门了...',
    next: 'boss_scorpion_king_pre_2',
    portrait: 'scorpion_king',
  },
  boss_scorpion_king_pre_2: {
    id: 'boss_scorpion_king_pre_2',
    speaker: '蝎皇',
    text: '沙漠的王者...不可侵犯！',
    action: 'start_boss:scorpion_king',
    portrait: 'scorpion_king',
  },
  boss_scorpion_king_post: {
    id: 'boss_scorpion_king_post',
    speaker: '蝎皇',
    text: '不可能...我是...沙漠之王...',
    action: 'give_items:star_fragment',
    portrait: 'scorpion_king',
  },

  boss_ice_dragon_pre: {
    id: 'boss_ice_dragon_pre',
    speaker: '冰龙',
    text: '汝...亦为碎片所引而来？',
    next: 'boss_ice_dragon_pre_2',
    portrait: 'ice_dragon',
  },
  boss_ice_dragon_pre_2: {
    id: 'boss_ice_dragon_pre_2',
    speaker: '冰龙',
    text: '吾已无法...控制自身...小心了...流浪者...',
    action: 'start_boss:ice_dragon',
    portrait: 'ice_dragon',
  },
  boss_ice_dragon_post: {
    id: 'boss_ice_dragon_post',
    speaker: '冰龙',
    text: '感谢...解脱...第三块碎片...归汝...',
    action: 'give_items:star_fragment',
    portrait: 'ice_dragon',
  },

  boss_void_devourer_pre: {
    id: 'boss_void_devourer_pre',
    speaker: '虚空吞噬者',
    text: '......',
    action: 'start_boss:void_devourer',
    portrait: 'void_devourer',
  },
  boss_void_devourer_post: {
    id: 'boss_void_devourer_post',
    speaker: '旁白',
    text: '虚空退却了，第四块碎片从裂隙中坠落。',
    action: 'give_items:star_fragment',
    portrait: 'void_devourer',
  },

  boss_fallen_saint_pre: {
    id: 'boss_fallen_saint_pre',
    speaker: '堕落圣者',
    text: '你来了...陨星的子嗣。',
    next: 'boss_fallen_saint_pre_2',
    portrait: 'fallen_saint',
  },
  boss_fallen_saint_pre_2: {
    id: 'boss_fallen_saint_pre_2',
    speaker: '堕落圣者',
    text: '你以为你在拯救世界？不...你只是在延续一个谎言！',
    next: 'boss_fallen_saint_pre_3',
    portrait: 'fallen_saint',
  },
  boss_fallen_saint_pre_3: {
    id: 'boss_fallen_saint_pre_3',
    speaker: '堕落圣者',
    text: '虚空不是敌人！它是这个世界的本源！让我证明给你看！',
    action: 'start_boss:fallen_saint',
    portrait: 'fallen_saint',
  },
  boss_fallen_saint_post: {
    id: 'boss_fallen_saint_post',
    speaker: '堕落圣者',
    text: '现在...做出你的选择吧。封印虚空之门...还是释放它的力量？',
    choices: [
      { text: '封印虚空之门', next: 'guard_captain_after_boss_good' },
      { text: '释放虚空之力', next: 'guard_captain_after_boss_bad' },
    ],
    portrait: 'fallen_saint',
  },
};

const quests: Record<string, QuestDef> = {
  forest_boss: {
    id: 'forest_boss',
    name: '平息古树灵',
    description: '前往翠影森林深处，平息狂暴的古树灵。',
    type: 'boss',
    target: 'ancient_tree_spirit',
    required: 1,
    reward: { exp: 200, gold: 100, items: ['star_fragment'] },
  },
  collect_iron: {
    id: 'collect_iron',
    name: '收集铁矿石',
    description: '在森林中收集铁矿石，交给铁匠格雷强化武器。',
    type: 'collect',
    target: 'iron_ore',
    required: 3,
    reward: { exp: 50, gold: 30 },
  },
  desert_boss: {
    id: 'desert_boss',
    name: '击败蝎皇',
    description: '深入灼沙荒漠遗迹，击败沙漠霸主蝎皇。',
    type: 'boss',
    target: 'scorpion_king',
    required: 1,
    reward: { exp: 350, gold: 150, items: ['star_fragment'] },
    prerequisite: 'forest_boss',
  },
  snow_boss: {
    id: 'snow_boss',
    name: '解救冰龙',
    description: '前往霜寂雪原，击败被虚空侵蚀的冰龙，回收星核碎片。',
    type: 'boss',
    target: 'ice_dragon',
    required: 1,
    reward: { exp: 500, gold: 200, items: ['star_fragment'] },
    prerequisite: 'desert_boss',
  },
  ruins_boss: {
    id: 'ruins_boss',
    name: '击退虚空吞噬者',
    description: '进入星落文明遗迹深处，击退虚空吞噬者，回收第四块星核碎片。',
    type: 'boss',
    target: 'void_devourer',
    required: 1,
    reward: { exp: 700, gold: 300, items: ['star_fragment'] },
    prerequisite: 'snow_boss',
  },
  final_boss: {
    id: 'final_boss',
    name: '最终决战',
    description: '前往暮光圣城大教堂，阻止堕落圣者打开虚空之门。',
    type: 'boss',
    target: 'fallen_saint',
    required: 1,
    reward: { exp: 1000, gold: 500, items: ['star_fragment'] },
    prerequisite: 'ruins_boss',
  },
  explore_forest: {
    id: 'explore_forest',
    name: '探索翠影森林',
    description: '探索翠影森林的每一个角落。',
    type: 'explore',
    target: 'forest',
    required: 1,
    reward: { exp: 100, gold: 50 },
  },
  kill_slimes: {
    id: 'kill_slimes',
    name: '清理史莱姆',
    description: '消灭翠影森林中横行的史莱姆。',
    type: 'kill',
    target: 'slime',
    required: 5,
    reward: { exp: 50, gold: 30, items: ['health_potion', 'health_potion'] },
  },
};

function getDialogue(id: string): DialogueLine | undefined {
  return dialogues[id];
}

function getQuest(id: string): QuestDef | undefined {
  return quests[id];
}

export { dialogues, quests, getDialogue, getQuest };
