# Part 6: Player Sprite (48x64) with all animations
L('// ===== PLAYER SPRITE (48x64) =====')
L('function drawPlayerBase(c,legPhase,cloakSway,swordAngle,bodyBob,facing){')
L('  const O=1,CD=2,CM=3,CL=4,CH=5,AD=6,AM=7,AH=8,AL=9,SD=10,SM=11,SH=12,SL=13,BD=14,BM=15,BH=16,HI=17,EY=18,BE=20,BU=21;')
L('  const by=4+bodyBob,cx=24;const dirMod=facing==="left"?-1:facing==="right"?1:0;')
L('  if(facing==="down"||facing==="up"){')
L('    const cloakW=10+Math.abs(cloakSway);c.ellipse(cx,22+by,cloakW,14,CM);c.ellipse(cx-1,21+by,cloakW-1,12,CL);c.ellipse(cx-2,19+by,cloakW-3,9,CH);c.ellipse(cx+2+cloakSway,23+by,7,11,CD);')
L('    c.line(cx-7+cloakSway*0.5,14+by,cx-8+cloakSway*0.5,34+by,CD);c.line(cx+7+cloakSway*0.5,14+by,cx+8+cloakSway*0.5,34+by,CD);')
L('    for(let i=0;i<6;i++){c.set(Math.round(cx-6+cloakSway*0.3),16+by+i*3,CL);c.set(Math.round(cx+5+cloakSway*0.3),17+by+i*3,CD)}')
L('    const leftLegX=cx-5,rightLegX=cx+3;const leftLegOff=Math.round(Math.sin(legPhase)*3),rightLegOff=Math.round(Math.sin(legPhase+Math.PI)*3);')
L('    c.rect(leftLegX,32+by,4,7+Math.max(0,leftLegOff),CM);c.rect(rightLegX,32+by,4,7+Math.max(0,rightLegOff),CM);c.set(leftLegX,32+by,CL);c.set(rightLegX,32+by,CL);')
L('    c.set(leftLegX+3,32+by+3+Math.max(0,leftLegOff),CD);c.set(rightLegX+3,32+by+3+Math.max(0,rightLegOff),CD);')
L('    c.rect(leftLegX-1,37+by+leftLegOff,5,4,BD);c.rect(rightLegX-1,37+by+rightLegOff,5,4,BD);c.set(leftLegX-1,37+by+leftLegOff,BM);c.set(rightLegX-1,37+by+rightLegOff,BM);c.set(leftLegX,37+by+leftLegOff,BH);c.set(rightLegX,37+by+rightLegOff,BH);')
L('    c.rect(cx-8,17+by,16,11,AM);c.rect(cx-7,17+by,14,3,AH);for(let i=-7;i<=7;i++)c.set(cx+i,17+by,AH);c.rect(cx-8,26+by,16,2,AD);c.rect(cx+4,18+by,5,8,AD);c.rect(cx-7,18+by,4,7,AL);')
L('    c.line(cx-4,18+by,cx-4,26+by,AD);c.line(cx+4,18+by,cx+4,26+by,AD);for(let i=0;i<3;i++){c.set(cx-3+i,19+by,AH);c.set(cx-3+i,23+by,AM)}')
L('    c.rect(cx-8,27+by,16,2,BE);c.set(cx-1,27+by,BU);c.set(cx,27+by,BU);c.set(cx+1,27+by,BU);')
L('    c.ellipse(cx-9,17+by,4,3,AM);c.ellipse(cx+9,17+by,4,3,AM);c.set(cx-11,16+by,AH);c.set(cx-10,16+by,AH);c.set(cx+10,16+by,AH);c.set(cx+11,16+by,AH);c.set(cx-11,19+by,AD);c.set(cx+11,19+by,AD);')
L('    if(facing==="down"){')
L('      c.ellipse(cx,11+by,6,6,SM);c.ellipse(cx-1,10+by,5,5,SH);c.ellipse(cx+1,12+by,4,4,SD);')
L('      c.ellipse(cx,8+by,7,4,BM);c.ellipse(cx-1,7+by,5,3,HL);c.ellipse(cx+1,9+by,5,3,HD);c.rect(cx-6,8+by,3,4,BM);c.rect(cx+3,8+by,3,4,HD);c.set(cx-6,8+by,HL);c.set(cx-6,9+by,BM);c.set(cx-6,10+by,HD);c.set(cx+5,8+by,HD);c.set(cx+5,9+by,HD);')
L('      c.set(cx-3,6+by,HL);c.set(cx-2,5+by,HM);c.set(cx-1,5+by,HL);c.set(cx,5+by,HM);c.set(cx+1,5+by,HD);c.set(cx+2,5+by,HD);c.set(cx+3,6+by,HD);')
L('      c.set(cx-3,11+by,EY);c.set(cx-2,11+by,SL);c.set(cx+2,11+by,EY);c.set(cx+3,11+by,SL);c.set(cx-2,13+by,SM);c.set(cx-1,13+by,SH);c.set(cx,13+by,SM);c.set(cx+1,13+by,SD);c.set(cx+2,13+by,SD);c.set(cx-1,14+by,SM);c.set(cx,14+by,SD);c.set(cx+1,14+by,SD);')
L('    }else{')
L('      c.ellipse(cx,11+by,6,5,SM);c.ellipse(cx-1,10+by,5,4,SH);c.ellipse(cx+1,12+by,4,3,SD);c.ellipse(cx,8+by,7,4,BM);c.ellipse(cx-1,7+by,5,3,HL);c.rect(cx-6,8+by,3,4,BM);c.rect(cx+3,8+by,3,4,BM);c.set(cx-6,8+by,HL);c.set(cx+5,8+by,HL);')
L('      c.set(cx-3,6+by,HL);c.set(cx-2,5+by,HM);c.set(cx,5+by,HM);c.set(cx+1,5+by,HL);c.set(cx+2,6+by,HL);')
L('      c.set(cx-2,12+by,SM);c.set(cx-1,12+by,SH);c.set(cx,12+by,SM);c.set(cx+1,12+by,SH);c.set(cx+2,12+by,SD);')
L('    }')
L('    const swordBaseX=cx+12,swordBaseY=18+by;')
L('    if(swordAngle===0){c.rect(swordBaseX,swordBaseY-8,2,10,BM);c.set(swordBaseX,swordBaseY-8,BH);c.set(swordBaseX,swordBaseY-7,BH);c.set(swordBaseX,swordBaseY-6,BH);c.rect(swordBaseX+2,swordBaseY-6,1,7,BD);c.rect(swordBaseX-1,swordBaseY+2,5,2,HI);c.set(swordBaseX,swordBaseY+2,BU)}')
L('    else if(swordAngle===1){c.rect(swordBaseX+2,swordBaseY-10,2,10,BM);c.set(swordBaseX+2,swordBaseY-10,BH);c.rect(swordBaseX+3,swordBaseY-8,1,7,BD);c.rect(swordBaseX,swordBaseY-2,5,2,HI);c.set(swordBaseX+1,swordBaseY-2,BU)}')
L('    else if(swordAngle===2){for(let i=0;i<10;i++){c.set(swordBaseX+i,swordBaseY+2-Math.round(i*0.8),BM);c.set(swordBaseX+i,swordBaseY+3-Math.round(i*0.8),BD)}c.set(swordBaseX,swordBaseY+2,BH);c.set(swordBaseX+1,swordBaseY+1,BH);c.rect(swordBaseX-1,swordBaseY+4,5,2,HI)}')
L('    else{c.rect(swordBaseX-3,swordBaseY+2,10,2,BM);c.set(swordBaseX-3,swordBaseY+2,BH);c.set(swordBaseX-2,swordBaseY+2,BH);c.set(swordBaseX-1,swordBaseY+2,BH);c.rect(swordBaseX+5,swordBaseY,1,6,BD);c.rect(swordBaseX+2,swordBaseY+4,5,2,HI)}')
L('    c.rect(cx-7+cloakSway*0.3,19+by,3,9,CM);c.set(cx-7+cloakSway*0.3,19+by,CL);c.rect(cx+4+cloakSway*0.3,19+by,3,9,CM);c.set(cx+4+cloakSway*0.3,19+by,CL);c.set(cx-6+cloakSway*0.3,26+by,SM);c.set(cx+6+cloakSway*0.3,26+by,SM);')
L('  }else{')
L('    const sideCx=facing==="left"?cx-2:cx+2;const swayDir=facing==="left"?-1:1;')
L('    c.ellipse(sideCx,22+by,8,13,CM);c.ellipse(sideCx-swayDir,21+by,7,11,CL);c.ellipse(sideCx-swayDir*2,19+by,5,8,CH);c.ellipse(sideCx+swayDir*2,24+by,6,10,CD);')
L('    c.line(sideCx-5*swayDir,14+by,sideCx-6*swayDir,33+by,CD);for(let i=0;i<5;i++)c.set(Math.round(sideCx-4*swayDir),16+by+i*3,CL);')
L('    const legX=sideCx-swayDir;const legOff=Math.round(Math.sin(legPhase)*3);c.rect(legX,32+by,4,7+Math.max(0,legOff),CM);c.set(legX,32+by,CL);c.set(legX+3,32+by+3+Math.max(0,legOff),CD);c.rect(legX-1,37+by+legOff,5,4,BD);c.set(legX-1,37+by+legOff,BM);c.set(legX,37+by+legOff,BH);c.set(legX+1,38+by+legOff,BM);')
L('    c.rect(sideCx-7,17+by,12,10,AM);c.rect(sideCx-6,17+by,10,3,AH);c.rect(sideCx-7,25+by,12,2,AD);c.rect(sideCx+2,18+by,4,7,AD);c.rect(sideCx-6,18+by,3,6,AL);c.line(sideCx-3,18+by,sideCx-3,25+by,AD);c.set(sideCx-2,19+by,AH);c.set(sideCx-1,19+by,AH);c.set(sideCx-2,23+by,AM);')
L('    c.rect(sideCx-7,26+by,12,2,BE);c.set(sideCx,26+by,BU);c.set(sideCx+1,26+by,BU);')
L('    c.ellipse(sideCx-8,17+by,3,2,AM);c.ellipse(sideCx+6,17+by,3,2,AM);c.set(sideCx-9,16+by,AH);c.set(sideCx+7,16+by,AH);c.set(sideCx-9,18+by,AD);')
L('    const headCx=sideCx-swayDir;c.ellipse(headCx,11+by,5,6,SM);c.ellipse(headCx-swayDir,10+by,4,5,SH);c.ellipse(headCx+swayDir,12+by,3,4,SD);')
L('    c.ellipse(headCx,7+by,6,4,BM);c.ellipse(headCx-swayDir,6+by,4,3,HL);c.ellipse(headCx+swayDir,8+by,4,3,HD);c.rect(headCx-4*swayDir,7+by,3,4,BM);c.set(headCx-4*swayDir,7+by,HL);c.set(headCx+2*swayDir,7+by,HD);')
L('    c.set(headCx-swayDir*2,5+by,HL);c.set(headCx-swayDir,4+by,HM);c.set(headCx,4+by,HL);c.set(headCx+swayDir,5+by,HD);c.set(headCx+swayDir*2,6+by,HD);')
L('    const eyeX=headCx+swayDir;c.set(eyeX,10+by,EY);c.set(eyeX+swayDir,10+by,SL);c.set(eyeX,12+by,SM);c.set(eyeX-swayDir,12+by,SH);c.set(eyeX,13+by,SD);')
L('    const armX=sideCx-5*swayDir;c.rect(armX,18+by,3,8,CM);c.set(armX,18+by,CL);c.set(armX,25+by,SM);')
L('    const swordX=sideCx+8*swayDir,swordY=18+by;if(swordAngle===0){c.rect(swordX,swordY-7,2,9,BM);c.set(swordX,swordY-7,BH);c.set(swordX,swordY-6,BH);c.rect(swordX+2,swordY-5,1,6,BD);c.rect(swordX-1,swordY+2,5,2,HI)}')
L('    else if(swordAngle===2){for(let i=0;i<9;i++){c.set(swordX+i*swayDir,swordY+1-Math.round(i*0.7),BM);c.set(swordX+i*swayDir,swordY+2-Math.round(i*0.7),BD)}c.rect(swordX-swayDir*2,swordY+3,5,2,HI)}')
L('  }')
L('  c.outline(O)')
L('}')

L('function createPlayerSprite(){')
L('  const idle=[];for(let i=0;i<4;i++){const c=new PixelCanvas(48,64);drawPlayerBase(c,0,Math.sin(i*0.8)*1.5,0,i%2===0?0:-1,"down");idle.push(c.toFrame())}')
L('  const walkDown=[];for(let i=0;i<4;i++){const c=new PixelCanvas(48,64);drawPlayerBase(c,i*Math.PI/2,Math.sin(i*Math.PI/2)*2,0,i%2===0?0:-1,"down");walkDown.push(c.toFrame())}')
L('  const walkUp=[];for(let i=0;i<4;i++){const c=new PixelCanvas(48,64);drawPlayerBase(c,i*Math.PI/2,-Math.sin(i*Math.PI/2)*2,0,i%2===0?0:-1,"up");walkUp.push(c.toFrame())}')
L('  const walkLeft=[];for(let i=0;i<4;i++){const c=new PixelCanvas(48,64);drawPlayerBase(c,i*Math.PI/2,-2,0,i%2===0?0:-1,"left");walkLeft.push(c.toFrame())}')
L('  const walkRight=[];for(let i=0;i<4;i++){const c=new PixelCanvas(48,64);drawPlayerBase(c,i*Math.PI/2,2,0,i%2===0?0:-1,"right");walkRight.push(c.toFrame())}')
L('  const attackDown=[];for(let i=0;i<4;i++){const c=new PixelCanvas(48,64);drawPlayerBase(c,0,i<2?i*2:(3-i)*2,i,i<2?-i*2:-(3-i)*2,"down");attackDown.push(c.toFrame())}')
L('  const attackUp=[];for(let i=0;i<4;i++){const c=new PixelCanvas(48,64);drawPlayerBase(c,0,0,i,i<2?-i*3:-(3-i)*3,"up");attackUp.push(c.toFrame())}')
L('  const attackSide=[];for(let i=0;i<4;i++){const c=new PixelCanvas(48,64);drawPlayerBase(c,0,i<2?i*2:(3-i)*2,i,i<2?-i:-(3-i),"right");attackSide.push(c.toFrame())}')
L('  const dash=[];')
L('  {const c1=new PixelCanvas(48,64);drawPlayerBase(c1,0,4,0,0,"down");for(let i=0;i<3;i++){c1.set(2+i*2,28+i,29);c1.set(2+i*2,29+i,29)}dash.push(c1.toFrame());')
L('  const c2=new PixelCanvas(48,64);drawPlayerBase(c2,0,-3,0,0,"down");for(let i=0;i<3;i++){c2.set(40-i*2,28+i,29);c2.set(40-i*2,29+i,29)}dash.push(c2.toFrame());')
L('  const c3=new PixelCanvas(48,64);drawPlayerBase(c3,0,0,0,-2,"down");dash.push(c3.toFrame())}')
L('  const hurt=[];{const c1=new PixelCanvas(48,64);drawPlayerBase(c1,0,0,0,0,"down");hurt.push(c1.toFrame());hurt.push(flashFrame(hurt[0],28))}')
L('  const skillCast=[];for(let i=0;i<4;i++){const c=new PixelCanvas(48,64);drawPlayerBase(c,0,0,0,0,"down");const glowR=4+i*3;c.circle(24,14,glowR,26);c.circle(24,14,glowR-2,27);if(i>=2){c.circle(24,14,glowR-4,28);c.set(24,12,29);c.set(23,13,29);c.set(25,13,29)}skillCast.push(c.toFrame())}')
L('  return{id:"player",palette:PP,animations:{idle:makeAnim("idle",idle,200,true),walk_down:makeAnim("walk_down",walkDown,120,true),walk_up:makeAnim("walk_up",walkUp,120,true),walk_left:makeAnim("walk_left",walkLeft,120,true),walk_right:makeAnim("walk_right",walkRight,120,true),attack_down:makeAnim("attack_down",attackDown,80,false),attack_up:makeAnim("attack_up",attackUp,80,false),attack_side:makeAnim("attack_side",attackSide,80,false),dash:makeAnim("dash",dash,60,false),hurt:makeAnim("hurt",hurt,100,false),skill_cast:makeAnim("skill_cast",skillCast,100,false)}}}')
L('}')

with open('/workspace/src/game/sprites.ts','a') as f: f.write('\n'.join(out))
print('Part 6 written:', len(out), 'lines')
