#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成 v2 蒸馏数据：代码(~68) + 9科(~162)，共约230条 -> /root/llm/finetune/data_teacher_v2.jsonl"""
import json

data = []

def add(inst, out):
    data.append({"instruction": inst, "output": out})

CODE = [
    ("用Python统计一句话中单词的个数",
     "```python\ndef word_count(s: str) -> int:\n    return len(s.split())\n```\n按空白符切分后统计长度即可，连续多个空格也会被正确处理。"),
    ("用Python去除字符串首尾空格并转大写",
     "```python\ndef clean(s: str) -> str:\n    return s.strip().upper()\n```\n`strip()` 去掉首尾空白，`upper()` 转大写，可链式调用。"),
    ("用Python判断一个字符串是否为回文串（忽略大小写）",
     "```python\ndef is_pal(s: str) -> bool:\n    s = s.lower()\n    return s == s[::-1]\n```\n先统一小写，再比较原串与反转串。"),
    ("用Python把字符串中的每个单词首字母大写",
     "```python\ndef title_case(s: str) -> str:\n    return s.title()\n```\n`str.title()` 会把每个单词首字母大写、其余小写。"),
    ("用Python实现字符串压缩，如 aabcccc 变为 a2b1c4",
     "```python\ndef compress(s: str) -> str:\n    if not s:\n        return s\n    res, cnt = [], 1\n    for i in range(1, len(s)):\n        if s[i] == s[i - 1]:\n            cnt += 1\n        else:\n            res.append(s[i - 1] + str(cnt))\n            cnt = 1\n    res.append(s[-1] + str(cnt))\n    return ''.join(res)\n```\n遍历统计连续相同字符的数量。"),
    ("用Python判断两个字符串是否为异位词（字母相同顺序不同）",
     "```python\ndef is_anagram(a: str, b: str) -> bool:\n    return sorted(a) == sorted(b)\n```\n排序后相等即为异位词；也可用 Counter 比较字符频次。"),
    ("用Python找出字符串中第一个不重复的字符",
     "```python\nfrom collections import Counter\ndef first_unique(s: str):\n    c = Counter(s)\n    for ch in s:\n        if c[ch] == 1:\n            return ch\n    return None\n```\n先统计频次，再按原顺序找第一个频次为1的字符。"),
    ("用Python实现将字符串按指定分隔符拆分成列表并反转每段",
     "```python\ndef split_reverse(s: str, sep: str):\n    return [seg[::-1] for seg in s.split(sep)]\n```\n用列表推导式对每个分段做切片反转。"),
    ("用Python把驼峰字符串拆分成语义片段，如 helloWorld -> hello World",
     "```python\nimport re\ndef split_camel(s: str) -> str:\n    return re.sub(r'(?<!^)(?=[A-Z])', ' ', s)\n```\n正则在大写字母前插入空格，实现驼峰拆分。"),
    ("用Python实现简单的行号输出：给多行文本每行加序号",
     "```python\ndef numbered(text: str) -> str:\n    lines = text.splitlines()\n    return '\\n'.join(f'{i + 1}. {ln}' for i, ln in enumerate(lines))\n```\nenumerate 同时取行号和内容，格式化拼接。"),
    ("用Python合并两个有序列表为一个有序列表",
     "```python\ndef merge_sorted(a, b):\n    i = j = 0\n    res = []\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            res.append(a[i]); i += 1\n        else:\n            res.append(b[j]); j += 1\n    res.extend(a[i:])\n    res.extend(b[j:])\n    return res\n```\n双指针归并，最后把剩余部分拼接上。"),
    ("用Python找出列表中第k大的元素",
     "```python\ndef kth_largest(nums, k):\n    return sorted(nums, reverse=True)[k - 1]\n```\n降序排序后取第k-1个下标即可；大数据量可用堆优化。"),
    ("用Python把列表按奇偶分离，偶数在前奇数在后",
     "```python\ndef partition_parity(nums):\n    return [x for x in nums if x % 2 == 0] + [x for x in nums if x % 2 != 0]\n```\n两次列表推导分别收集偶数和奇数再拼接。"),
    ("用Python将矩阵（二维列表）转置",
     "```python\ndef transpose(m):\n    return [list(row) for row in zip(*m)]\n```\n`zip(*m)` 把每列变成一组，再转回列表。"),
    ("用Python计算列表中相邻元素差的绝对值列表",
     "```python\ndef diffs(nums):\n    return [abs(nums[i] - nums[i + 1]) for i in range(len(nums) - 1)]\n```\n遍历相邻下标求差的绝对值。"),
    ("用Python找到列表中重复次数最多的元素",
     "```python\nfrom collections import Counter\ndef most_common(lst):\n    return Counter(lst).most_common(1)[0][0]\n```\nCounter 统计后取最频繁的项。"),
    ("用Python实现列表的滚动右移k位",
     "```python\ndef rotate(nums, k):\n    k %= len(nums)\n    return nums[-k:] + nums[:-k] if k else nums[:]\n```\n取末尾k个放到前面；k对长度取模处理超过长度的情况。"),
    ("用Python求两个列表的交集（去重）",
     "```python\ndef intersect(a, b):\n    return list(set(a) & set(b))\n```\n集合取交集运算符 `&` 再转列表。"),
    ("用Python把嵌套列表展平成单层",
     "```python\ndef flatten(lst):\n    res = []\n    for x in lst:\n        if isinstance(x, list):\n            res.extend(flatten(x))\n        else:\n            res.append(x)\n    return res\n```\n递归处理，遇到子列表继续展开。"),
    ("用Python找出数组中的多数元素（出现次数超过一半）",
     "```python\ndef majority(nums):\n    cand, cnt = None, 0\n    for x in nums:\n        if cnt == 0:\n            cand, cnt = x, 1\n        elif x == cand:\n            cnt += 1\n        else:\n            cnt -= 1\n    return cand\n```\nBoyer-Moore 投票法，一趟扫描即可，O(n) 时间 O(1) 空间。"),
    ("用Python实现快速排序",
     "```python\ndef quicksort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    mid = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quicksort(left) + mid + quicksort(right)\n```\n选基准，递归排序左右两部分后拼接。"),
    ("用Python实现选择排序",
     "```python\ndef selection_sort(arr):\n    n = len(arr)\n    for i in range(n - 1):\n        m = i\n        for j in range(i + 1, n):\n            if arr[j] < arr[m]:\n                m = j\n        arr[i], arr[m] = arr[m], arr[i]\n    return arr\n```\n每轮从未排序区选出最小元素放到前面。"),
    ("用Python实现插入排序",
     "```python\ndef insertion_sort(arr):\n    for i in range(1, len(arr)):\n        key = arr[i]\n        j = i - 1\n        while j >= 0 and arr[j] > key:\n            arr[j + 1] = arr[j]\n            j -= 1\n        arr[j + 1] = key\n    return arr\n```\n把当前元素插入到已排序区间的正确位置。"),
    ("用Python实现线性查找",
     "```python\ndef linear_search(arr, target):\n    for i, x in enumerate(arr):\n        if x == target:\n            return i\n    return -1\n```\n逐个比较，找到返回下标，否则返回-1。"),
    ("用Python实现递归求阶乘",
     "```python\ndef factorial(n: int) -> int:\n    return 1 if n <= 1 else n * factorial(n - 1)\n```\n递归基为n<=1返回1，否则n乘以(n-1)的阶乘。"),
    ("用Python实现递归求斐波那契数列第n项",
     "```python\ndef fib_rec(n: int) -> int:\n    if n <= 1:\n        return n\n    return fib_rec(n - 1) + fib_rec(n - 2)\n```\n递归定义清晰，但重复计算多；大数据量建议改用迭代或记忆化。"),
    ("用Python实现二分查找的递归版本",
     "```python\ndef bs(arr, lo, hi, target):\n    if lo > hi:\n        return -1\n    mid = (lo + hi) // 2\n    if arr[mid] == target:\n        return mid\n    if arr[mid] < target:\n        return bs(arr, mid + 1, hi, target)\n    return bs(arr, lo, mid - 1, target)\n```\n递归实现，每次折半缩小查找区间。"),
    ("用Python判断一个整数是否为2的幂",
     "```python\ndef is_power_of_two(n: int) -> bool:\n    return n > 0 and (n & (n - 1)) == 0\n```\n2的幂二进制只有一位为1，n与n-1按位与为0。"),
    ("用Python求1到n的和（用公式）",
     "```python\ndef sum_n(n: int) -> int:\n    return n * (n + 1) // 2\n```\n等差数列求和公式，O(1) 完成，避免循环。"),
    ("用Python实现十进制转二进制字符串",
     "```python\ndef to_bin(n: int) -> str:\n    return bin(n)[2:] if n >= 0 else '-' + bin(-n)[2:]\n```\n`bin()` 输出带0b前缀，切片去掉即可。"),
    ("用Python实现一个简单的栈（基于列表）",
     "```python\nclass Stack:\n    def __init__(self):\n        self.items = []\n    def push(self, x):\n        self.items.append(x)\n    def pop(self):\n        return self.items.pop()\n    def peek(self):\n        return self.items[-1]\n    def is_empty(self):\n        return not self.items\n```\n列表的 append/pop 天然支持后进先出。"),
    ("用Python实现一个简单的队列（基于列表）",
     "```python\nfrom collections import deque\nclass Queue:\n    def __init__(self):\n        self.q = deque()\n    def enqueue(self, x):\n        self.q.append(x)\n    def dequeue(self):\n        return self.q.popleft()\n    def is_empty(self):\n        return not self.q\n```\n用 deque 避免列表头部弹出的 O(n) 开销。"),
    ("用Python实现LRU缓存的思路和代码",
     "```python\nfrom collections import OrderedDict\nclass LRUCache:\n    def __init__(self, cap):\n        self.cap = cap\n        self.d = OrderedDict()\n    def get(self, key):\n        if key not in self.d:\n            return -1\n        self.d.move_to_end(key)\n        return self.d[key]\n    def put(self, key, val):\n        if key in self.d:\n            self.d.move_to_end(key)\n        self.d[key] = val\n        if len(self.d) > self.cap:\n            self.d.popitem(last=False)\n```\nOrderedDict 记录插入顺序，命中即移到末尾，超容量弹出最久未用。"),
    ("用Python实现链表节点并实现尾插法构建链表",
     "```python\nclass Node:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef build(vals):\n    dummy = Node()\n    cur = dummy\n    for v in vals:\n        cur.next = Node(v)\n        cur = cur.next\n    return dummy.next\n```\n用哑节点简化边界处理，逐个创建节点串联。"),
    ("用Python求链表的长度",
     "```python\ndef length(head):\n    cnt = 0\n    cur = head\n    while cur:\n        cnt += 1\n        cur = cur.next\n    return cnt\n```\n从头遍历到空节点，计数即可。"),
    ("用Python判断链表中是否存在环（快慢指针）",
     "```python\ndef has_cycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow is fast:\n            return True\n    return False\n```\n快指针每次走两步，若存在环二者必相遇。"),
    ("用Python实现二叉树节点并求最大深度",
     "```python\nclass TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef max_depth(root):\n    if not root:\n        return 0\n    return 1 + max(max_depth(root.left), max_depth(root.right))\n```\n递归求左右子树深度取最大加一。"),
    ("用Python实现二叉树的前序遍历（递归）",
     "```python\ndef preorder(root):\n    if not root:\n        return []\n    return [root.val] + preorder(root.left) + preorder(root.right)\n```\n先访问根，再递归左子树和右子树。"),
    ("用Python统计一个整数列表的频次字典",
     "```python\ndef freq(nums):\n    d = {}\n    for x in nums:\n        d[x] = d.get(x, 0) + 1\n    return d\n```\n用 `dict.get` 带默认值0累加计数。"),
    ("用Python按键值对字典排序（按值降序）",
     "```python\ndef sort_by_value(d, reverse=True):\n    return dict(sorted(d.items(), key=lambda kv: kv[1], reverse=reverse))\n```\nsorted 指定 key 取值为排序依据，reverse 控制升降序。"),
    ("用Python合并两个字典，后者覆盖前者",
     "```python\ndef merge_dict(a, b):\n    return {**a, **b}\n```\n字典解包合并，后面的b会覆盖a中相同键。Python3.9+ 也可用 `a | b`。"),
    ("用Python求两个集合的并集、交集、差集",
     "```python\ndef set_ops(a, b):\n    return (a | b, a & b, a - b)\n```\n`|`并集、`&`交集、`-`差集，返回三个集合。"),
    ("用Python把两个列表按索引配对成字典",
     "```python\ndef pair(keys, vals):\n    return dict(zip(keys, vals))\n```\nzip 按索引配对，dict 转成键值映射。"),
    ("用Python求一个数的平方根（近似，不使用math.sqrt）",
     "```python\ndef sqrt_approx(n, eps=1e-9):\n    if n < 0:\n        raise ValueError('negative')\n    if n == 0:\n        return 0.0\n    x = n\n    while True:\n        nx = (x + n / x) / 2\n        if abs(nx - x) < eps:\n            return nx\n        x = nx\n```\n牛顿迭代法，每次取均值逼近平方根。"),
    ("用Python判断一个数是否为完全平方数",
     "```python\ndef is_perfect_square(n):\n    r = int(n ** 0.5)\n    return r * r == n\n```\n开方取整后平方是否等于原数。"),
    ("用Python生成指定范围内的所有素数（埃氏筛）",
     "```python\ndef primes_upto(n):\n    sieve = [True] * (n + 1)\n    sieve[0] = sieve[1] = False\n    for i in range(2, int(n ** 0.5) + 1):\n        if sieve[i]:\n            for j in range(i * i, n + 1, i):\n                sieve[j] = False\n    return [i for i in range(2, n + 1) if sieve[i]]\n```\n埃氏筛，从每个素数的平方开始标记倍数。"),
    ("用Python计算两个数的最大公约数（辗转相除法，不用math）",
     "```python\ndef gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return abs(a)\n```\n辗转相除，b为0时a即最大公约数。"),
    ("用Python求最小公倍数",
     "```python\ndef lcm(a, b):\n    return abs(a * b) // gcd(a, b)\n\ndef gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return abs(a)\n```\n两数之积除以最大公约数即为最小公倍数。"),
    ("用Python计算列表中所有数的乘积",
     "```python\nimport math\ndef product(nums):\n    return math.prod(nums)\n```\nPython3.8+ 的 `math.prod` 直接返回乘积；也可用 reduce。"),
    ("用Python生成一个包含1到n所有偶数的列表",
     "```python\ndef evens(n):\n    return [x for x in range(1, n + 1) if x % 2 == 0]\n```\n列表推导式过滤偶数。"),
    ("用Python写一个装饰器，打印函数执行时间",
     "```python\nimport time\ndef timing(fn):\n    def wrapper(*args, **kwargs):\n        t0 = time.time()\n        r = fn(*args, **kwargs)\n        print(f'{fn.__name__} 耗时 {time.time() - t0:.4f}s')\n        return r\n    return wrapper\n```\n装饰器包裹原函数，前后取时间差并打印。"),
    ("用Python用lambda表达式实现两个数相加",
     "```python\nadd = lambda a, b: a + b\n```\nlambda 定义匿名函数，调用 `add(2, 3)` 返回5。"),
    ("用Python用map把列表中每个数平方",
     "```python\ndef square_all(nums):\n    return list(map(lambda x: x * x, nums))\n```\nmap 配合 lambda 逐元素平方，转列表输出。"),
    ("用Python用filter筛选出正数",
     "```python\ndef positives(nums):\n    return list(filter(lambda x: x > 0, nums))\n```\nfilter 按条件保留满足的元素。"),
    ("用Python用reduce计算列表累加和",
     "```python\nfrom functools import reduce\ndef total(nums):\n    return reduce(lambda a, b: a + b, nums, 0)\n```\nreduce 迭代归并，初始值0逐项累加。"),
    ("用Python定义一个矩形类，含面积和周长方法",
     "```python\nclass Rectangle:\n    def __init__(self, w, h):\n        self.w = w\n        self.h = h\n    def area(self):\n        return self.w * self.h\n    def perimeter(self):\n        return 2 * (self.w + self.h)\n```\n构造方法存宽高，area与perimeter分别计算。"),
    ("用Python定义一个银行账户类，支持存款取款",
     "```python\nclass Account:\n    def __init__(self, name, balance=0):\n        self.name = name\n        self.balance = balance\n    def deposit(self, amount):\n        self.balance += amount\n    def withdraw(self, amount):\n        if amount > self.balance:\n            raise ValueError('余额不足')\n        self.balance -= amount\n    def __str__(self):\n        return f'{self.name} 余额 {self.balance}'\n```\n取款前校验余额，`__str__` 便于打印账户信息。"),
    ("用Python定义一个学生类，含添加成绩和平均分方法",
     "```python\nclass Student:\n    def __init__(self, name):\n        self.name = name\n        self.scores = []\n    def add_score(self, s):\n        self.scores.append(s)\n    def avg(self):\n        return sum(self.scores) / len(self.scores) if self.scores else 0\n```\n成绩存列表，平均分用sum/len计算。"),
    ("用Python演示类的继承：狗类继承动物类",
     "```python\nclass Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return '...'\n\nclass Dog(Animal):\n    def speak(self):\n        return '汪汪'\n```\n子类Dog继承Animal，重写speak方法实现多态。"),
    ("用Python读取文本文件并统计行数",
     "```python\ndef count_lines(path):\n    with open(path, encoding='utf-8') as f:\n        return sum(1 for _ in f)\n```\nwith 打开文件安全关闭，生成器逐行计数。"),
    ("用Python把列表逐行写入文本文件",
     "```python\ndef write_lines(path, lines):\n    with open(path, 'w', encoding='utf-8') as f:\n        f.writelines(line + '\\n' for line in lines)\n```\nwritelines 配合生成器逐行写入并补换行。"),
    ("用Python读取CSV文件并打印每行",
     "```python\nimport csv\ndef read_csv(path):\n    with open(path, newline='', encoding='utf-8') as f:\n        return list(csv.reader(f))\n```\ncsv.reader 逐行解析，返回行列表。"),
    ("用JavaScript实现节流函数",
     "```javascript\nfunction throttle(fn, delay = 300) {\n  let last = 0;\n  return function (...args) {\n    const now = Date.now();\n    if (now - last >= delay) {\n      last = now;\n      fn.apply(this, args);\n    }\n  };\n}\n```\n记录上次执行时间，间隔达到delay才执行，适合滚动事件。"),
    ("用SQL查询表中所有学生的姓名和年龄",
     "```sql\nSELECT name, age FROM students;\n```\nSELECT 指定列，FROM 指定表。"),
    ("用SQL按分数降序排序前10名",
     "```sql\nSELECT * FROM students ORDER BY score DESC LIMIT 10;\n```\nORDER BY ... DESC 降序，LIMIT 10 取前10行。"),
    ("用SQL统计每个班级的人数",
     "```sql\nSELECT class, COUNT(*) FROM students GROUP BY class;\n```\nGROUP BY 按班级分组，COUNT 统计每组人数。"),
    ("用CSS实现文本居中",
     "```css\n.center {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n```\nflex 布局，水平垂直都居中。"),
    ("用HTML写一个带标题和段落的页面",
     "```html\n<!DOCTYPE html>\n<html>\n<head><title>示例</title></head>\n<body>\n  <h1>标题</h1>\n  <p>这是一段文字。</p>\n</body>\n</html>\n```\nh1为一级标题，p为段落。"),
]
for inst, out in CODE:
    add(inst, out)

SUBJECT = {
"语文": [
    ("《静夜思》中表达思乡之情的两句诗是什么？",
     "“举头望明月，低头思故乡。”出自李白的《静夜思》，前两句是“床前明月光，疑是地上霜”。"),
    ("“春风又绿江南岸”出自哪首诗？作者是谁？",
     "出自王安石的《泊船瓜洲》，全句为“春风又绿江南岸，明月何时照我还”，一个“绿”字生动写出春到江南的景象。"),
    ("《水调歌头·明月几时有》中“但愿人长久”的下一句是？",
     "下一句是“千里共婵娟”。此句出自苏轼的《水调歌头》，表达对亲人的美好祝愿。"),
    ("“醉翁之意不在酒”出自哪部作品？",
     "出自欧阳修的《醉翁亭记》，“醉翁之意不在酒，在乎山水之间也”，后用来比喻本意不在此而别有用心。"),
    ("“学而不思则罔，思而不学则殆”是什么意思？",
     "只学习不思考就会迷惑，只思考不学习就会疑惑而无所收获。出自《论语》，强调学习与思考结合。"),
    ("《岳阳楼记》中表现作者远大抱负的名句是什么？",
     "“先天下之忧而忧，后天下之乐而乐”，出自范仲淹的《岳阳楼记》，表现了以天下为己任的博大胸怀。"),
    ("“山重水复疑无路，柳暗花明又一村”出自谁的作品？",
     "出自南宋诗人陆游的《游山西村》，后比喻在困境中又出现新的转机。"),
    ("《木兰诗》中表现木兰代父从军原因的诗句是什么？",
     "“阿爷无大儿，木兰无长兄，愿为市鞍马，从此替爷征。”木兰因父亲年迈无子而替父从军。"),
    ("《出师表》的作者是谁？文中“鞠躬尽瘁，死而后已”表达了什么？",
     "作者是诸葛亮。《出师表》是诸葛亮北伐前上呈后主刘禅的表文，“鞠躬尽瘁，死而后已”表达他竭尽全力、至死不渝的忠心。"),
    ("什么是比喻？举一个例子。",
     "比喻是用与本体有相似点的事物（喻体）来说明本体的修辞手法。如“月亮像白玉盘”，把月亮比作白玉盘。"),
    ("什么是拟人？举一个例子。",
     "拟人是把物当做人来写，赋予物人的动作、情感或神态。如“小草偷偷地从土里钻出来”，用“钻”“偷偷”赋予小草人的动作。"),
    ("什么是排比？有什么作用？",
     "排比是把三个或三个以上结构相同或相似、内容相关、语气一致的短语或句子排列起来。作用是增强语势，加强节奏感，突出强调。"),
    ("记叙文的六要素是什么？",
     "记叙文的六要素是：时间、地点、人物、起因、经过、结果。"),
    ("说明文中常用的说明方法有哪些？",
     "常见说明方法有：举例子、列数字、作比较、打比方、分类别、下定义、摹状貌等。"),
    ("《孔乙己》的作者是谁？主人公有什么特点？",
     "作者是鲁迅，选自《呐喊》。孔乙己是受封建科举制度毒害的读书人，迂腐可笑、自命清高又善良，处于社会底层。"),
    ("“当局者迷，旁观者清”可以用哪句诗来诠释？",
     "可用苏轼《题西林壁》中的“不识庐山真面目，只缘身在此山中”，都说明置身其中反而看不清全局。"),
    ("默写：会当凌绝顶，______。",
     "一览众山小。（杜甫《望岳》）"),
    ("《论语》中论述学习与思考关系的句子是？",
     "“学而不思则罔，思而不学则殆。”（《论语·为政》）"),
],
"数学": [
    ("-5的相反数是？",
     "-5的相反数是5。相反数是指绝对值相等、符号相反的两个数。"),
    ("计算：(-2)³ = ?",
     "(-2)³ = (-2)×(-2)×(-2) = -8。注意负数的奇数次幂仍为负。"),
    ("已知|x|=3，则x等于多少？",
     "x = 3 或 x = -3。绝对值的几何意义是数轴上到原点的距离，因此有两个解。"),
    ("一元一次方程 2x + 3 = 11 的解是？",
     "移项得 2x = 11 - 3 = 8，两边同除以2，得 x = 4。"),
    ("解不等式：3x - 6 > 0",
     "移项得 3x > 6，两边同除以3（正数，不等号方向不变），得 x > 2。"),
    ("两条直线互相垂直，它们的斜率之积是多少？",
     "在平面直角坐标系中，两条互相垂直的直线斜率之积为 -1（其中一条斜率不存在时除外，如竖直与水平线）。"),
    ("三角形内角和是多少度？外角和呢？",
     "三角形内角和为180°；外角和为360°。"),
    ("等腰三角形的一个底角是50°，顶角是多少度？",
     "两底角相等，各50°，顶角 = 180° - 50° - 50° = 80°。"),
    ("平行四边形的面积公式是什么？",
     "平行四边形的面积 = 底 × 高，即 S = ah（a为底，h为底上的高）。"),
    ("圆的面积和周长的公式分别是什么？",
     "圆的面积 S = πr²，周长 C = 2πr（r为半径）。"),
    ("扇形面积公式是什么？",
     "扇形面积 S = (n/360)πr²，其中n为扇形圆心角度数，r为半径；也可写作 S = (1/2)lr，l为弧长。"),
    ("一次函数的一般形式是什么？它的图像是什么？",
     "一次函数一般形式为 y = kx + b（k≠0），图像是一条直线。k决定直线倾斜方向，b决定与y轴的交点。"),
    ("二次函数 y = ax² + bx + c 的图像是什么？开口方向由什么决定？",
     "图像是抛物线。开口方向由二次项系数a决定：a>0开口向上，a<0开口向下。"),
    ("一元二次方程的求根公式是什么？",
     "对于 ax² + bx + c = 0（a≠0），判别式 Δ = b² - 4ac。当Δ≥0时，x = [-b ± √(b²-4ac)] / (2a)。"),
    ("计算：√9 + √16 = ?",
     "√9 = 3，√16 = 4，所以 √9 + √16 = 3 + 4 = 7。"),
    ("分解因式：x² - 9 = ?",
     "x² - 9 = (x + 3)(x - 3)，利用平方差公式 a² - b² = (a+b)(a-b)。"),
    ("概率为0.3的事件在10次独立试验中，平均会发生几次？",
     "平均发生 10 × 0.3 = 3 次。概率反映的是大量重复试验中的频率趋向。"),
    ("一组数据的中位数如何确定？",
     "先把数据从小到大排序。若数据个数为奇数，中位数是中间那个数；若为偶数，中位数是中间两个数的平均数。"),
],
"英语": [
    ("一般现在时中，主语为第三人称单数时，动词play应如何变化？",
     "play → plays，直接在词尾加 -s。一般现在时第三人称单数动词加-s或-es。"),
    ("she has 还是 she have？为什么？",
     "用 she has。因为主语she是第三人称单数，一般现在时要用 has。"),
    ("写出 go、see、eat 的过去式。",
     "go → went，see → saw，eat → ate。它们都是不规则动词，需单独记忆。"),
    ("There is 和 There are 怎么选择？",
     "看后面名词的单复数：单数或不可数用 There is，复数用 There are。如 There is a book. / There are two books.。"),
    ("介词 on 用于时间时表示什么？举一个例子。",
     "on 用于具体某一天或某一天的上午/下午/晚上，如 on Monday、on May 1st、on Sunday morning。"),
    ("比较级和最高级的构成规则中，单词 tall 怎么变？",
     "tall → taller → tallest，单音节词一般在词尾加 -er 和 -est。"),
    ("my / mine 的区别是什么？",
     "my 是形容词性物主代词，后面要接名词，如 my book；mine 是名词性物主代词，独立使用，如 The book is mine。"),
    ("一般将来时 be going to 的用法是什么？",
     "be going to + 动词原形，表示打算做某事或有迹象表明将要发生的事。如 I am going to visit Beijing tomorrow.。"),
    ("被动语态的基本结构是什么？",
     "被动语态基本结构为 be + 过去分词。如 The cake was eaten by Tom.（蛋糕被汤姆吃了）。"),
    ("句子 How old are you? 的肯定回答是什么？",
     "I am ... years old. 例如 I am thirteen years old.（我十三岁）。"),
    ("单词 interesting 和 interested 的用法区别？",
     "interesting 描述事物“令人感兴趣的”，如 The book is interesting.；interested 描述人“对...感兴趣的”，如 I am interested in music.。"),
    ("英语中可数名词变复数的规则，以辅音字母+y结尾的单词怎么变？",
     "把 y 变 i 再加 -es，如 city → cities、baby → babies。"),
    ("现在完成时的基本结构是什么？",
     "现在完成时基本结构为 have/has + 过去分词，表示过去的动作对现在造成的影响或持续到现在。如 I have finished my homework.。"),
    ("What 和 Which 在提问时的区别？",
     "What 表示“什么”，范围不定，如 What is your name?；Which 表示“哪一个”，在有限范围内选择，如 Which color do you like, red or blue?。"),
    ("情态动词 can 后面接动词的什么形式？",
     "can 后面接动词原形，如 I can swim.（我会游泳）。"),
    ("把句子 She is a doctor. 变为一般疑问句。",
     "Is she a doctor?（她是一名医生吗？）含有be动词的句子，把be动词提到句首即可。"),
    ("月份 January 是一年中的第几个月？",
     "January（一月）是一年中的第一个月，缩写为 Jan.。"),
    ("用英语翻译“请把门关上。”",
     "Please close the door. 或 Please shut the door.。"),
],
"物理": [
    ("声音是由什么产生的？在真空中能传播吗？",
     "声音是由物体振动产生的。声音的传播需要介质，真空中不能传播声音。"),
    ("光在真空中的传播速度是多少？",
     "光在真空中的传播速度约为 3×10⁸ m/s，即每秒30万千米。"),
    ("平面镜成像的特点是什么？",
     "平面镜成的是正立、等大的虚像，像与物到镜面的距离相等，像与物的连线与镜面垂直（即像与物关于镜面对称）。"),
    ("凸透镜成倒立放大的实像时，物距满足什么条件？",
     "当物距大于一倍焦距小于二倍焦距（f < u < 2f）时，成倒立放大的实像，如投影仪。"),
    ("力是改变物体运动状态的原因吗？还是维持运动的原因？",
     "力是改变物体运动状态的原因，而不是维持运动的原因。物体不受力时将保持静止或匀速直线运动状态（牛顿第一定律）。"),
    ("重力的方向是什么？大小如何计算？",
     "重力的方向总是竖直向下的。大小 G = mg，其中g取9.8 N/kg。"),
    ("增大摩擦力的方法有哪些？",
     "增大压力、增大接触面的粗糙程度。例如鞋底有花纹、刹车时用力捏闸。"),
    ("液体压强与哪些因素有关？",
     "液体压强与液体密度和深度有关，公式 p = ρgh。深度越深、密度越大，压强越大。"),
    ("浮力的大小与什么有关？阿基米德原理是什么？",
     "阿基米德原理：浸在液体中的物体受到的浮力等于它排开的液体所受的重力，F浮 = ρ液gV排。浮力大小与液体密度和排开液体的体积有关。"),
    ("什么是功？功的计算公式是什么？",
     "功等于力与物体在力的方向上移动距离的乘积，W = Fs，单位是焦耳（J）。做功的两个必要因素：一是作用在物体上的力，二是物体在力的方向上移动距离。"),
    ("功率的物理意义和公式是什么？",
     "功率表示做功的快慢，公式 P = W/t，单位是瓦特（W）。功率越大，做功越快。"),
    ("动能大小与什么因素有关？",
     "动能与物体的质量和速度有关：质量越大、速度越大，动能越大。"),
    ("串联电路中电流有什么特点？",
     "串联电路中电流处处相等，即 I = I₁ = I₂。总电压等于各用电器电压之和。"),
    ("并联电路中电压有什么特点？",
     "并联电路各支路两端的电压相等，都等于电源电压。干路电流等于各支路电流之和。"),
    ("欧姆定律的公式是什么？变形公式有哪些？",
     "欧姆定律：I = U/R。变形：U = IR，R = U/I。导体中的电流与电压成正比，与电阻成反比。"),
    ("家庭电路中电压是多少？触电事故的原因是什么？",
     "我国家庭电路电压为220V。触电事故是因为人体直接或间接接触火线，与大地或零线构成回路，有较大电流通过人体。"),
    ("电功（电能）的计算公式是什么？",
     "电功 W = UIt = Pt，单位是焦耳（J）或千瓦时（kW·h），1 kW·h = 3.6×10⁶ J。"),
    ("热传递的三种方式是什么？",
     "热传递的三种方式：传导、对流、辐射。"),
],
"化学": [
    ("氧气的化学式是什么？它的密度比空气大还是小？",
     "氧气的化学式是 O₂，密度略大于空气，不易溶于水，常用向上排空气法或排水法收集。"),
    ("二氧化碳能使澄清石灰水变浑浊，这是化学变化还是物理变化？",
     "是化学变化。因为生成了新的物质碳酸钙，使石灰水变浑浊。"),
    ("水的净化方法中，除去不溶性杂质常用什么操作？",
     "常用过滤操作，可除去水中的不溶性杂质；蒸馏可得到纯净水。"),
    ("实验室制取氧气常用的药品有哪些？",
     "常用过氧化氢溶液和二氧化锰（催化剂），或加热高锰酸钾、氯酸钾制取氧气。"),
    ("铁在氧气中燃烧的现象是什么？生成什么物质？",
     "铁在氧气中剧烈燃烧，火星四射，放出大量热，生成黑色固体四氧化三铁（Fe₃O₄）。"),
    ("质量守恒定律的内容是什么？",
     "参加化学反应的各物质的质量总和等于反应后生成的各物质的质量总和。原因是化学反应前后原子的种类、数目和质量都不变。"),
    ("化学方程式 2H₂ + O₂ 点燃 2H₂O 表示什么？",
     "表示2个氢分子与1个氧分子在点燃条件下反应生成2个水分子，即氢气在氧气中燃烧生成水。"),
    ("碳酸钙的化学式是什么？实验室如何检验二氧化碳？",
     "碳酸钙的化学式是 CaCO₃。检验二氧化碳：把气体通入澄清石灰水，若变浑浊则为二氧化碳。"),
    ("酸雨的形成与哪些气体有关？",
     "酸雨主要与二氧化硫（SO₂）、氮氧化物（NOₓ）等气体排放有关，它们溶于水形成酸。"),
    ("pH<7的溶液呈什么性？pH=7呢？",
     "pH<7 呈酸性，pH=7 呈中性，pH>7 呈碱性。pH越小酸性越强。"),
    ("氯化钠的化学式及俗称是什么？",
     "氯化钠化学式 NaCl，俗称食盐，是调味品的主要成分，也是重要的化工原料。"),
    ("氢气作为燃料的优点有哪些？",
     "氢气燃烧只生成水，无污染；热值高；来源广泛（水）。但制取和储存成本较高。"),
    ("如何检验氧气？",
     "用带火星的木条伸入集气瓶，若木条复燃，则证明是氧气。"),
    ("分子和原子的主要区别是什么？",
     "在化学变化中，分子可以再分为原子，原子不可再分。分子是保持物质化学性质的最小粒子，原子是化学变化中的最小粒子。"),
    ("地壳中含量最高的元素是什么？",
     "地壳中含量最高的元素是氧（O），其次为硅（Si）。"),
    ("生石灰的化学式是什么？加水后有什么变化？",
     "生石灰是氧化钙 CaO。加水发生放热反应生成熟石灰 Ca(OH)₂，同时放出大量热。"),
    ("配平：Fe + O₂ → Fe₃O₄",
     "3Fe + 2O₂ 点燃 Fe₃O₄。铁原子：左3右3，氧原子：左4右4，配平完成。"),
    ("元素符号中，Na表示什么？",
     "Na表示钠元素，也表示一个钠原子。元素符号的宏观含义表示一种元素，微观含义表示该元素的一个原子。"),
],
"生物": [
    ("除病毒外，生物体结构和功能的基本单位是什么？",
     "是细胞。除病毒外，所有生物都由细胞构成，细胞是生命活动的基本单位。"),
    ("细胞膜的功能是什么？",
     "细胞膜具有保护细胞内部结构、控制物质进出细胞的功能，使细胞具有相对稳定的内部环境。"),
    ("动植物细胞共有的基本结构有哪些？",
     "动植物细胞共有的结构：细胞膜、细胞质、细胞核、线粒体。动物细胞没有细胞壁、叶绿体和液泡。"),
    ("细胞分裂过程中变化最明显的是什么？",
     "细胞分裂时变化最明显的是染色体，染色体先复制加倍再平均分配到两个子细胞中，保证遗传物质稳定。"),
    ("绿色植物进行光合作用的场所和条件是什么？",
     "场所是叶绿体，条件是光。光合作用把二氧化碳和水合成有机物并释放氧气。"),
    ("呼吸作用的公式是什么？",
     "呼吸作用：有机物 + 氧气 → 二氧化碳 + 水 + 能量（主要在细胞内的线粒体中进行）。"),
    ("叶片的结构包括哪些部分？",
     "叶片由表皮（上下表皮）、叶肉和叶脉三部分组成，气孔分布在表皮上，是气体交换的通道。"),
    ("人体消化系统中，消化和吸收的主要场所是什么？",
     "是小肠。小肠长且内壁有皱襞和绒毛，增大了消化吸收面积。"),
    ("人体血液的组成包括哪些？",
     "血液由血浆和血细胞组成，血细胞包括红细胞、白细胞和血小板。红细胞运输氧气，白细胞吞噬病菌，血小板止血凝血。"),
    ("心脏的四个腔是什么？体循环和肺循环的起点分别在哪？",
     "心脏四腔：左心房、左心室、右心房、右心室。体循环起点是左心室，肺循环起点是右心室。"),
    ("人体泌尿系统中形成尿液的器官是什么？",
     "是肾脏。尿液的形成包括肾小球的过滤作用（形成原尿）和肾小管的重吸收作用两个过程。"),
    ("视觉形成的部位在哪里？",
     "视觉最终在大脑皮层的视觉中枢形成。眼球中晶状体、视网膜等负责成像，视网膜上形成的是倒立的像。"),
    ("反射和反射弧的关系是什么？",
     "反射弧是完成反射活动的结构基础，包括感受器、传入神经、神经中枢、传出神经、效应器五部分。反射必须通过反射弧完成。"),
    ("遗传物质DNA主要存在于细胞的哪个结构中？",
     "DNA主要存在于细胞核中，细胞核是遗传信息库，染色体由DNA和蛋白质组成。"),
    ("一对相对性状中，显性性状和隐性性状如何判断？",
     "具有相对性状的纯合亲本杂交，子一代表现出的性状是显性性状，未表现的是隐性性状。如高茎×矮茎杂交后代全为高茎，则高茎为显性。"),
    ("生态系统由哪两部分组成？食物链中能量的流动有什么特点？",
     "生态系统由生物部分（生产者、消费者、分解者）和非生物部分（阳光、水、空气等）组成。能量沿食物链单向流动、逐级递减。"),
    ("人体缺少哪种维生素易患夜盲症？",
     "缺少维生素A易患夜盲症。缺乏维生素C易患坏血病。"),
    ("动物和植物在细胞结构上的主要区别是什么？",
     "植物细胞有细胞壁、叶绿体和液泡，动物细胞没有这三种结构。"),
],
"历史": [
    ("我国境内目前已确认的最早古人类是什么？生活在哪个时代？",
     "是元谋人，距今约170万年，生活在云南元谋，是我国境内目前已确认的最早的古人类。"),
    ("北京人生活在什么时期？他们使用什么工具？",
     "北京人生活在距今约70万—20万年的旧石器时代早期，使用打制石器，会使用天然火。"),
    ("夏朝是谁建立的？它标志着什么？",
     "夏朝由禹的儿子启建立（公元前2070年左右），标志着我国早期国家的产生，世袭制取代禅让制。"),
    ("商朝最后一个暴君是谁？",
     "是商纣王。他荒淫残暴，最终被周武王在牧野之战中打败，商朝灭亡。"),
    ("西周实行的分封制有什么作用？",
     "分封制加强了周天子对地方的控制，扩大了统治范围，但也埋下了诸侯割据的隐患。"),
    ("春秋时期第一个称霸的诸侯是谁？",
     "是齐桓公。他任用管仲为相进行改革，以“尊王攘夷”为口号，成为春秋首霸。"),
    ("秦统一六国是哪一年？秦朝采取哪些巩固统一的措施？",
     "公元前221年秦始皇统一六国。措施：统一文字（小篆）、统一货币（圆形方孔半两钱）、统一度量衡、修建驰道、北筑长城等。"),
    ("汉武帝时期，谁两次出使西域？这条路叫什么？",
     "张骞两次出使西域，开辟了陆上丝绸之路，促进了中外经济文化交流。"),
    ("东汉末年的官渡之战和赤壁之战分别有什么意义？",
     "官渡之战（200年）曹操以少胜多打败袁绍，为统一北方奠定基础；赤壁之战（208年）孙刘联军以少胜多打败曹操，奠定三国鼎立的基础。"),
    ("隋朝大运河的中心、南北起止点分别是什么？",
     "大运河以洛阳为中心，北达涿郡（今北京），南至余杭（今杭州），全长两千多千米，连接了海河、黄河、淮河、长江、钱塘江五大水系。"),
    ("唐朝的全盛时期，出现“贞观之治”和“开元盛世”的皇帝分别是谁？",
     "“贞观之治”是唐太宗李世民在位时期；“开元盛世”是唐玄宗李隆基在位前期。"),
    ("北宋毕昇发明了什么？有什么意义？",
     "毕昇发明了活字印刷术，比欧洲早约400年，推动了世界文化的传播。"),
    ("郑和下西洋发生在哪个朝代？最远到达哪里？",
     "发生在明朝（1405—1433年），郑和先后七次下西洋，最远到达非洲东海岸和红海沿岸，是世界航海史上的壮举。"),
    ("1840年鸦片战争后，中国社会性质发生了什么变化？",
     "鸦片战争使中国开始沦为半殖民地半封建社会，是中国近代史的开端。"),
    ("辛亥革命发生在哪一年？它的历史意义是什么？",
     "1911年（武昌起义），孙中山领导。辛亥革命推翻了清王朝，结束了中国两千多年的君主专制制度，建立了中华民国，使民主共和观念深入人心。"),
    ("五四运动爆发的时间和意义是什么？",
     "1919年5月4日在北京爆发。五四运动是一次彻底地反帝反封建的爱国运动，是中国新民主主义革命的开端。"),
    ("1949年10月1日发生了什么重大历史事件？",
     "中华人民共和国成立。开国大典在北京天安门广场举行，标志着中国新民主主义革命的胜利，中国人民从此站起来了。"),
    ("工业革命最早发生在哪个国家？它使人类进入什么时代？",
     "工业革命最早发生在英国，18世纪60年代开始，瓦特改良蒸汽机后，人类进入“蒸汽时代”。"),
],
"地理": [
    ("地球的形状是什么？",
     "地球是一个两极稍扁、赤道略鼓的不规则球体。麦哲伦船队环球航行证实了地球是球体。"),
    ("地球的赤道周长和平均半径分别约是多少？",
     "赤道周长约4万千米，平均半径约6371千米。"),
    ("经线和纬线有什么特点？",
     "经线是连接南北两极的半圆，所有经线等长，指示南北方向；纬线是圆圈，长度从赤道向两极递减，指示东西方向。"),
    ("赤道的纬度是多少？南北半球的分界线是什么？",
     "赤道纬度是0°。赤道是南北半球的分界线，也是南北纬的分界。"),
    ("地球自转的方向和产生的现象是什么？",
     "地球自转方向是自西向东，周期为一天，产生了昼夜交替和时间的差异。"),
    ("中国有哪四大高原？",
     "青藏高原、内蒙古高原、黄土高原、云贵高原。其中青藏高原被称为“世界屋脊”。"),
    ("中国第一大河和第一长河是？",
     "长江是我国长度最长、水量最大、流域面积最广的河流，全长约6300千米。"),
    ("黄河的发源地在哪里？它注入哪个海？",
     "黄河发源于青藏高原的巴颜喀拉山，注入渤海。"),
    ("秦岭—淮河一线的地理意义有哪些？",
     "秦岭—淮河一线大致是我国1月0℃等温线、800毫米年等降水量线经过的地方，是暖温带与亚热带、湿润区与半湿润区、南方与北方地区的分界线。"),
    ("世界面积最大的大洲和大洋分别是什么？",
     "面积最大的大洲是亚洲（约4400万平方千米），面积最大的大洋是太平洋。"),
    ("世界上面积最大的国家是？",
     "俄罗斯，面积约1700多万平方千米，地跨亚欧两大洲。"),
    ("世界上人口最多的国家是？",
     "中国，人口超过14亿；印度人口也超过14亿，位居第二。"),
    ("七大洲中，跨纬度最广的大洲是？",
     "亚洲，北至北极圈以北，南至赤道以南，跨纬度最广。"),
    ("等高线地形图中，等高线密集表示什么？",
     "等高线密集表示坡度陡，等高线稀疏表示坡度缓。"),
    ("气候的两个基本要素是什么？",
     "气温和降水是气候的两个基本要素。"),
    ("我国降水量空间分布的总体规律是什么？",
     "我国年降水量从东南沿海向西北内陆递减，大致由东南向西北逐渐减少。"),
    ("地球公转产生了哪些地理现象？",
     "地球公转产生了四季更替、昼夜长短变化和五带的划分。"),
    ("世界上最大的沙漠是？位于哪个洲？",
     "撒哈拉沙漠，位于非洲北部，是世界上面积最大的沙漠。"),
],
"道德与法治": [
    ("我国的根本大法是什么？",
     "宪法是我国的根本大法，具有最高的法律地位、法律权威和法律效力。"),
    ("宪法规定我国的国家性质（国体）是什么？",
     "我国是工人阶级领导的、以工农联盟为基础的人民民主专政的社会主义国家。"),
    ("公民最基本的权利是什么？",
     "人身自由权是公民最基本、最重要的权利，是公民享有其他一切权利的先决条件。"),
    ("未成年人保护法规定的六大保护是什么？",
     "家庭保护、学校保护、社会保护、网络保护、政府保护、司法保护，合称“六道防线”。"),
    ("社会主义核心价值观的三个层面分别是什么？",
     "国家层面：富强、民主、文明、和谐；社会层面：自由、平等、公正、法治；个人层面：爱国、敬业、诚信、友善。"),
    ("法律的特征有哪些？",
     "法律由国家制定或认可，靠国家强制力保证实施，对全体社会成员具有普遍约束力。"),
    ("违法行为分为哪几类？",
     "按违反的法律类别分为行政违法行为、民事违法行为和刑事违法行为；按危害程度分为一般违法行为和严重违法行为（犯罪）。"),
    ("犯罪的基本特征是什么？",
     "犯罪具有三个基本特征：严重社会危害性、刑事违法性、应受刑罚处罚性。"),
    ("青少年如何自我保护，预防违法犯罪？",
     "增强法律意识，明辨是非，自觉抵制不良诱惑；遇到侵害依法维权，学会运用法律武器保护自己；谨慎交友，远离不良行为。"),
    ("规则与自由的关系是什么？",
     "自由和规则不可分，社会规则划定了自由的边界，自由是在规则范围内的自由，人们遵守规则正是对自由的最大保障。"),
    ("诚信的重要性是什么？",
     "诚信是中华民族的传统美德，是社会主义核心价值观的要求；诚信是一个人安身立命之本，是企业生存发展之道，也是构建和谐社会的需要。"),
    ("我国公民行使监督权的渠道有哪些？",
     "可以通过人大代表或直接向有关部门反映，可通过书信、电话、网络等方式，还可通过新闻媒体等渠道行使监督权。"),
    ("公平正义的意义是什么？",
     "公平正义是社会和谐稳定、国家长治久安的重要基础；维护公平正义是社会主义法治的价值追求，有利于保障人民合法权益。"),
    ("民族团结有什么重要性？",
     "民族团结是国家统一和社会稳定的重要保障，是各民族共同繁荣发展的前提，我国坚持民族平等、团结、互助、和谐。"),
    ("人民代表大会制度在我国政治生活中的地位如何？",
     "人民代表大会制度是我国的根本政治制度，是人民当家作主的根本途径和最高实现形式，一切权力属于人民。"),
    ("依法治国的新十六字方针是什么？",
     "科学立法、严格执法、公正司法、全民守法。"),
    ("未成年人为什么需要特殊保护？",
     "未成年人身心发育尚不成熟，缺乏自我保护能力，辨别是非和自我控制能力较弱，容易受到不良因素的影响和不法侵害。"),
    ("如何正确行使公民权利？",
     "公民在行使权利时，不得损害国家的、社会的、集体的利益和其他公民的合法权利；要在法律允许的范围内，以合法方式行使权利。"),
],
}

for subj, items in SUBJECT.items():
    for q, a in items:
        add(q, a)

seen = set()
out = []
for d in data:
    if d["instruction"] not in seen:
        seen.add(d["instruction"])
        out.append(d)

with open("/root/llm/finetune/data_teacher_v2.jsonl", "w", encoding="utf-8") as f:
    for d in out:
        f.write(json.dumps(d, ensure_ascii=False) + "\n")

print(f"共生成 {len(out)} 条 (代码 {len(CODE)} + 科目 {len(out)-len(CODE)})")
